"""empty message

Revision ID: a51bd33f847b
Revises: 3b5ff4980e34
Create Date: 2024-09-19 12:28:42.514929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a51bd33f847b'
down_revision = '3b5ff4980e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_at')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
